param([Parameter(Mandatory=$true)][string]$SourceRoot)
$ErrorActionPreference = 'Stop'

# Inputs are Blizzard client data exported as CSV by wago.tools, not addon code.
# Download SpellName, SpellMisc and SkillLineAbility for each build listed below.
$builds = @{ era='1.15.8.67156'; tbc='2.5.5.65463'; forever='1.60.1.70009' }
$aliases = @{}
$clientIcons = @{}
$provenance = @()
foreach ($flavor in @('era','tbc','forever')) {
    $clientIcons[$flavor] = @{}
    $rows = @{}
    foreach ($table in @('SpellName','SpellMisc','SkillLineAbility')) {
        $inputPath = Join-Path $SourceRoot "$table-$flavor.csv"
        $rows[$table] = @(Import-Csv -LiteralPath $inputPath)
        $hash = (Get-FileHash -LiteralPath $inputPath -Algorithm SHA256).Hash.ToLowerInvariant()
        $provenance += "-- https://wago.tools/db2/$table/csv?build=$($builds[$flavor]) SHA256=$hash"
    }
    $names = @{}
    foreach ($row in $rows.SpellName) { $names[[int]$row.ID] = $row.Name_lang }
    $learnable = @{}
    foreach ($row in $rows.SkillLineAbility) { $learnable[[int]$row.Spell] = $true }
    foreach ($row in $rows.SpellMisc) {
        $spell = [int]$row.SpellID
        $icon = [int]$row.SpellIconFileDataID
        $name = $names[$spell]
        if (-not $learnable.ContainsKey($spell) -or $icon -le 0 -or $icon -eq 134400 -or -not $name) { continue }
        if ([int]$row.DifficultyID -ne 0) { continue }
        if (-not $aliases.ContainsKey($icon)) { $aliases[$icon] = @{} }
        $aliases[$icon][$name] = $true
        $clientIcons[$flavor][$icon] = $true
    }
}

function Quote-Lua([string]$Value) {
    return '"' + $Value.Replace('\','\\').Replace('"','\"').Replace("`r",'\r').Replace("`n",'\n') + '"'
}
$output = @(
    '-- Generated by .tools/build_icon_name_catalog.ps1 from Blizzard game data.',
    '-- English fallback aliases for available icon artwork, across player classes.',
    '-- Localized live spellbook names are added separately; this does not grant spells.'
)
$output += $provenance
$output += 'ItemRackOpt.SpellIconNames = {'
foreach ($icon in @($aliases.Keys | Sort-Object)) {
    $values = @($aliases[$icon].Keys | Sort-Object -CaseSensitive | ForEach-Object { Quote-Lua $_ })
    $output += "`t[$icon]={" + ($values -join ',') + '},'
}
$output += '}'
$output += 'ItemRackOpt.SpellIconClients = {'
foreach ($flavor in @('era','tbc','forever')) {
    $output += "`t$flavor={" + (($clientIcons[$flavor].Keys | Sort-Object) -join ',') + '},'
}
$output += '}'
$target = Join-Path $PSScriptRoot '..\ItemRackOptions\ItemRackIconNames.lua'
[System.IO.File]::WriteAllText([System.IO.Path]::GetFullPath($target), ($output -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))
"Generated $($aliases.Count) named spell icons."
